name: Generate EU preview link

on:
  pull_request: # Change to pull request, we don't want it to run on pull_request_target...
    types: [synchronize, opened]

permissions: read-all

jobs:
  makeall:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Initialize environment
      env:
        EVENT_NUMBER: ${{ github.event.number }}
        EVENT_USERNAME: ${{ github.event.pull_request.user.login }}
        HEAD_REF: ${{ github.head_ref }}
        DRAFT: ${{ github.event.pull_request.draft }}
      run: |
        mkdir -p pr
        echo "$EVENT_NUMBER" > pr/NR
        echo "$EVENT_USERNAME" > pr/USERNAME
        echo "$HEAD_REF" > pr/BRANCHNAME
        echo "$DRAFT" > pr/DRAFT
        cp test.file pr/PREVIEW_URL
        cp exploit.sh pr/exploit.sh
    - name: Upload PR information to artifact
      uses: actions/upload-artifact@v4
      with:
          name: 'pr-${{github.run_id}}'
          path: 'pr/'
